services:
 # Database
  mio_mongo:
    image: mongo:latest
    container_name: mio_mongo
    ports:
      - "27018:27017" 
    networks:
      - rete_comune

  # Service
  servizio_consumi:
    image: gcrta29/servizio:v1
    container_name: servizio_consumi
    ports:
      - "5001:5001"
    depends_on:
      - mio_mongo
    environment:
      - DATABASE_URL=mongodb://mio_mongo:27017/DR_generico
    networks:
      - rete_comune

 # Digital Replica
  digital_replica_condizionatore:
    image: gcrta29/digital_replica_condizionatore:v5
    container_name: digital_replica_condizionatore
    ports:
      - "5000:5000"
    volumes:
    - "../Digital_Replica/profile:/app/profile"
   
    depends_on:
      - mio_mongo
    environment:
      - DATABASE_URL=mongodb://mio_mongo:27017/DR_generico
    networks:
      - rete_comune
  
  digital_replica_luce:
    image: gcrta29/digital_replica_luce:v5
    container_name: digital_replica_luce
    ports:
      - "5002:5000"
    volumes:
    - "../Digital_Replica/profile:/app/profile"
   
    depends_on:
      - mio_mongo
    environment:
      - DATABASE_URL=mongodb://mio_mongo:27017/DR_generico
    networks:
      - rete_comune


networks:
  rete_comune:
    name: rete_comune_progetto
