services:
 # Database
  mio_mongo:
    image: mongo:latest
    container_name: mio_mongo
    ports:
      - "27018:27017" 
    networks:
      - rete_comune

  # Service
  servizio_consumi:
    image: gcrta29/servizio:v1
    container_name: servizio_consumi
    ports:
      - "5001:5001"
    depends_on:
      - mio_mongo
    networks:
      - rete_comune

 # Digital Replica
  digital_replica_app:
    image: gcrta29/digital_replica:v1
    container_name: digital_replica
    ports:
      - "5000:5000"
    volumes:
    - "../Digital_Replica/profile:/app/profile"
   
    depends_on:
      - mio_mongo
    networks:
      - rete_comune

networks:
  rete_comune:
    name: rete_comune_progetto
